### ISSUE TITLE
您好，关于训练的问题

### ISSUE THREAD

**Issue by nopeiyu** [zhangzjn/APB2FaceV2#3]
我最近尝试训练APB2FaceV2，我直接用v2的G生成器替换V1的生成器，能进行训练，但是训练效果较差，想向您请教一下：
1.损失函数相比v1需要进行较大的修改吗
2.在训练landmark2face网络的时候，audio2landmark网络参数会同时训练吗
希望能抽时间指导一下，非常感谢！

**Comment by zhangzjn** [comment]
@nopeiyu 如下
1.详情可参见论文。
2.A2L可以单独训练，联合训练可以得到稍微更优的结果。
