### ISSUE TITLE
Full code

### ISSUE THREAD

**Issue by vogoriachko** [zhangzjn/APB2FaceV2#4]
@zhangzjn When will you publish full code? Or it will not be realized ?

**Comment by JohannesTK** [comment]
+1

**Comment by zhangzjn** [comment]
The notification date is January 22, 2021. I am sorry that the complete training code will be released at that moment.
![image](https://user-images.githubusercontent.com/26211183/102953080-78e28500-450b-11eb-9ac0-aa6dcafa5141.png)

**Comment by zhangzjn** [comment]
The entire code is open source
