### ISSUE TITLE
How to use this on custom videos

### ISSUE THREAD

**Issue by niladridutt** [zhangzjn/APB2FaceV2#7]
Right now the dataloader can only parse ANNVii dataset it seems. How can I use it on custom videos? How to get the .t7 file?

**Comment by zhangzjn** [comment]
You need to get synchronized image, audio, and landmark data for your own dataset. Details to generate the .t7 file can be found in `data/AnnScripts/script_AnnVI.py`.

**Comment by niladridutt** [comment]
Thank you so much for your reply and uploading the scripts!
What do you mean by "synchronized audio, image, pose, landmark, and blink information" in the paper? And how do I get it (for example dlib 68 shape predictor?)? It'll be really helpful if you could explain what is synced images. Thanks!

**Comment by zhangzjn** [comment]
- Synchronization means that the image and audio have the same timestamp, so that the audio can be used to control the facial movement.
- For the landmark detector, you can refer to `https://github.com/davisking/dlib` or `https://www.faceplusplus.com.cn/face-detection`

**Comment by niladridutt** [comment]
Thanks!
Do you have any script that generates the landmarks of the images and cropped images in the format needed by script_AnnVI.py ? It'll be very helpful if you could upload them as well. 
Essentially if you have a script that generates landmark files from the video it'll be great

**Comment by zhangzjn** [comment]
I'm sorry, but you can refer to [str_landmark](https://github.com/zhangzjn/APB2FaceV2/blob/c76e1f560f070382004556a943d16299097c2fcb/data/AnnScripts/data_utils.py#L41) to create the custom dataset that matches `script_AnnVI.py`.

**Comment by niladridutt** [comment]
Alright. I'm using dlib 68 shape predictors, it only has landmarks; what do you recommend to get the pose and eye information as well? Will the code need any modifications to only work with 68 landmarks instead of the 112 or so generated by face plus plus API.

**Comment by niladridutt** [comment]
@zhangzjn No problem, I've generated landmarks and head pose using dlib. What's the expected format [here](https://github.com/zhangzjn/APB2FaceV2/blob/c76e1f560f070382004556a943d16299097c2fcb/data/AnnScripts/data_utils.py#L41)?
Will it have problems if I don't input eye blink information?
